config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'admin/index'
  get 'admin/test'

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store_asset.rb
class StoreAsset < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
  end

  def test
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :get_layout
protected
	def get_layout
	  # if self.class.parent == Admin
	    "admin"
	  # else
	    # "application"
	  # end
	end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
Hello

app/views/admin/test.html.erb
HELLO WELCOME BUDDY :D

app/views/layouts/_admin_header.html.erb
            <!-- Header -->
            <header class="top-head container-fluid">
                <button type="button" class="navbar-toggle pull-left">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <!-- Search -->
                <form role="search" class="navbar-left app-search pull-left hidden-xs">
                  <input type="text" placeholder="Search..." class="form-control">
                  <a href="#"><i class="fa fa-search"></i></a>
                </form>
                
                <!-- Left navbar -->
                <nav class=" navbar-default" role="navigation">
                    <ul class="nav navbar-nav hidden-xs">
                        <li class="dropdown">
                          <a data-toggle="dropdown" class="dropdown-toggle" href="#">English <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="#">German</a></li>
                                <li><a href="#">French</a></li>
                                <li><a href="#">Italian</a></li>
                                <li><a href="#">Spanish</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Files</a></li>
                    </ul>

                    <!-- Right navbar -->
                    <ul class="nav navbar-nav navbar-right top-menu top-right-menu">  
                        <!-- mesages -->  
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <i class="zmdi zmdi-email-open"></i>
                                <span class="badge badge-sm up bg-purple count">4</span>
                            </a>
                            <ul class="dropdown-menu extended fadeInUp animated nicescroll" tabindex="5001">
                                <li>
                                    <p>Messages</p>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="pull-left"><img src="/assets/admin/avatar-2.jpg" class="img-circle thumb-sm m-r-15" alt="img"></span>
                                        <span class="block"><strong>John smith</strong></span>
                                        <span class="media-body block">New tasks needs to be done<br><small class="text-muted">10 seconds ago</small></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="pull-left"><img src="/assets/admin/avatar-3.jpg" class="img-circle thumb-sm m-r-15" alt="img"></span>
                                        <span class="block"><strong>John smith</strong></span>
                                        <span class="media-body block">New tasks needs to be done<br><small class="text-muted">3 minutes ago</small></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="pull-left"><img src="/assets/admin/avatar-4.jpg" class="img-circle thumb-sm m-r-15" alt="img"></span>
                                        <span class="block"><strong>John smith</strong></span>
                                        <span class="media-body block">New tasks needs to be done<br><small class="text-muted">10 minutes ago</small></span>
                                    </a>
                                </li>
                                <li>
                                    <p><a href="inbox.html" class="text-right">See all Messages</a></p>
                                </li>
                            </ul>
                        </li>
                        <!-- /messages -->
                        <!-- Notification -->
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <i class="zmdi zmdi-notifications-none"></i>
                                <span class="badge badge-sm up bg-pink count">3</span>
                            </a>
                            <ul class="dropdown-menu extended fadeInUp animated nicescroll" tabindex="5002">
                                <li class="noti-header">
                                    <p>Notifications</p>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="pull-left"><i class="fa fa-user-plus fa-2x text-info"></i></span>
                                        <span>New user registered<br><small class="text-muted">5 minutes ago</small></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="pull-left"><i class="fa fa-diamond fa-2x text-primary"></i></span>
                                        <span>Use animate.css<br><small class="text-muted">5 minutes ago</small></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="pull-left"><i class="fa fa-bell-o fa-2x text-danger"></i></span>
                                        <span>Send project demo files to client<br><small class="text-muted">1 hour ago</small></span>
                                    </a>
                                </li>
                                
                                <li>
                                    <p><a href="#" class="text-right">See all notifications</a></p>
                                </li>
                            </ul>
                        </li>
                        <!-- /Notification -->

                        <!-- user login dropdown start-->
                        <li class="dropdown text-center">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <img alt="" src="/assets/admin/avatar-2.jpg" class="img-circle profile-img thumb-sm">
                                <span class="username">John Deo </span> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu pro-menu fadeInUp animated" tabindex="5003" style="overflow: hidden; outline: none;">
                                <li><a href="profile.html"><i class="fa fa-briefcase"></i>Profile</a></li>
                                <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                                <li><a href="#"><i class="fa fa-bell"></i> Friends <span class="label label-info pull-right mail-info">5</span></a></li>
                                <li><a href="#"><i class="fa fa-sign-out"></i> Log Out</a></li>
                            </ul>
                        </li>
                        <!-- user login dropdown end -->       
                    </ul>
                    <!-- End right navbar -->
                </nav>
                
            </header>
            <!-- Header Ends -->

app/views/layouts/_admin_left_accordian.html.erb
  <!-- Navbar Start -->
  <nav class="navigation">
      <ul class="list-unstyled">
          <li class="active"><a href="index-2.html"><i class="zmdi zmdi-view-dashboard"></i> <span class="nav-label">Dashboard</span></a></li>
          <li class="has-submenu">
              <a href="#"><i class="zmdi zmdi-format-underlined"></i> <span class="nav-label">User Interface</span><span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                  <li><a href="ui-typography.html">Typography</a></li>
                  <li><a href="ui-buttons.html">Buttons</a></li>
                  <li><a href="ui-icons.html">Icons</a></li>
                  <li><a href="ui-panels.html">Panels</a></li>
                  <li><a href="ui-tabs-accordions.html">Tabs &amp; Accordions</a></li>
                  <li><a href="ui-modals.html">Modals</a></li>
                  <li><a href="ui-bootstrap.html">BS Elements</a></li>
                  <li><a href="ui-progressbars.html">Progress Bars</a></li>
                  <li><a href="ui-notification.html">Notification</a></li>
                  <li><a href="ui-sweet-alert.html">Sweet-Alert</a></li>
                  <li><a><%= link_to "Guest Orders", admin_test_path %></a></li>
              </ul>
          </li>
          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-album"></i> <span class="nav-label">Components</span><span class="badge bg-warning">New</span></a>
              <ul class="list-unstyled">
                  <li><a href="components-grid.html">Grid</a></li>
                  <li><a href="components-portlets.html">Portlets</a></li>
                  <li><a href="components-widgets.html">Widgets</a></li>
                  <li><a href="components-nestable-list.html">Nesteble</a></li>
                  <li><a href="components-calendar.html">Calendar</a></li>
                  <li><a href="components-sliders.html">Range Slider</a></li>
              </ul>
          </li>
          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-collection-text"></i> <span class="nav-label">Forms</span><span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                  <li><a href="form-elements.html">General Elements</a></li>
                  <li><a href="form-validation.html">Form Validation</a></li>
                  <li><a href="form-advanced.html">Advanced Form</a></li>
                  <li><a href="form-wizard.html">Form Wizard</a></li>
                  <li><a href="form-editor.html">WYSIWYG Editor</a></li>
                  <li><a href="form-codeeditor.html">Code Editors</a></li>
                  <li><a href="form-uploads.html">Multiple File Upload</a></li>
                  <li><a href="form-imagecrop.html">Image Crop</a></li>
                  <li><a href="form-xeditable.html">X-Editable</a></li>
              </ul>
          </li>
          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-format-list-bulleted"></i> <span class="nav-label">Data Tables</span><span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                  <li><a href="tables.html">Basic Tables</a></li>
                  <li><a href="tables-datatable.html">Data Table</a></li>
                  <li><a href="tables-editable.html">Editable Table</a></li>
                  <li><a href="tables-responsive.html">Responsive Table</a></li>
              </ul>
          </li>
          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-chart"></i> <span class="nav-label">Charts</span><span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                  <li><a href="charts-morris.html">Morris Chart</a></li>
                  <li><a href="charts-chartjs.html">Chartjs</a></li>
                  <li><a href="charts-flot.html">Flot Chart</a></li>
                  <li><a href="charts-rickshaw.html">Rickshaw Chart</a></li>
                  <li><a href="charts-peity.html">Peity Chart</a></li>
                  <li><a href="charts-c3.html">C3 Chart</a></li>
                  <li><a href="charts-other.html">Other Chart</a></li>
              </ul>
          </li>

          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-email"></i> <span class="nav-label">Mail</span><span class="badge bg-success">7</span></a>
              <ul class="list-unstyled">
                  <li><a href="email-inbox.html">Inbox</a></li>
                  <li><a href="email-compose.html">Compose Mail</a></li>
                  <li><a href="email-read.html">View Mail</a></li>
                  <li><a href="email-templates.html">Email Templates</a></li>
              </ul>
          </li>

          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-map"></i> <span class="nav-label">Maps</span><span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                  <li><a href="maps-google.html"> Google Map</a></li>
                  <li><a href="maps-vector.html"> Vector Map</a></li>
              </ul>
          </li>
          <li class="has-submenu"><a href="#"><i class="zmdi zmdi-collection-item"></i> <span class="nav-label">Pages</span><span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                  <li><a href="pages-profile.html">Profile</a></li>
                  <li><a href="pages-timeline.html">Timeline</a></li>
                  <li><a href="pages-invoice.html">Invoice</a></li>
                  <li><a href="pages-contact.html">Contact-list</a></li>
                  <li><a href="pages-login.html">Login</a></li>
                  <li><a href="pages-register.html">Register</a></li>
                  <li><a href="pages-recoverpw.html">Recover Password</a></li>
                  <li><a href="pages-lock-screen.html">Lock Screen</a></li>
                  <li><a href="pages-blank.html">Blank Page</a></li>
                  <li><a href="pages-404.html">404 Error</a></li>
                  <li><a href="pages-404_alt.html">404 alt</a></li>
                  <li><a href="pages-500.html">500 Error</a></li>
              </ul>
          </li>
      </ul>
  </nav>

app/views/layouts/_landing_footer.html.erb
        <!--Start [Footer]-->

        <footer>
            <section id="footer">
                <div class="container text-center">
                    <div class="row">

                        <h2>The Best Startup For Your <span class="bolder">App</span></h2>
                        <div class="col-md-12"> 

                            <p class="mb20 title-para">                                 

                                Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt 
                                ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.                                                                               
                            </p>
                        </div>

                        <div class="mb20">

                            <a class="btn default_color available-btn colored-button float-button-light">
                                <i class="fa fa-mobile"></i>
                                <em> Available on </em>
                                App store
                            </a>
                            <a class="btn default_color available-btn colored-button float-button-light">
                                <i class="fa fa-android"></i>
                                <em> Available on </em>
                                Google Play
                            </a>                                 
                        </div>

                        <p class="footer-copyright mb0"> Your App &copy; <span id="copyright-year"><%= Date.today.strftime("%Y") %></span>. All rights reserved </p>

                    </div>
                </div>
            </section>

        </footer>
        <!--End [Footer]--> 
        <!-- Move to up -->
        <a class="btn btn-lg waves-effect waves-light scrollup"><i class="fa fa-arrow-up"></i></a>

app/views/layouts/_landing_header.html.erb
        <!--Nav Menu Starts-->
        <nav class="navbar default">
            <div class="container mob-logo"> 
                <div class="navbar-header col-sm-2 tablet-logo">
                    <button type="button" class="navbar-toggle mob-menu" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                    </button>
                    <div class="mobile-sidebar">                                                  
                        <span class="sidebar-btn btn fa-bar-hide" data-action="toggle" data-side="right">
                            <i class="fa fa-bars"></i>
                        </span>                  
                    </div>                        
                    <a href="index-cloud.html" class="brand-logo">

                        <img src="/assets/logo.png" alt="appestia logo">

                    </a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav pull-right">
                        <li class="active">
                            <a href="#home">Home</a>
                        </li>                      
                        <li>
                            <a href="#magical_feature">Features</a>
                        </li>
                        <li>
                            <a href="#why_us">Whyus</a>
                        </li>
                        <li>
                            <a href="#screenshots">Screenshots</a>
                        </li>
                        <li>
                            <a href="#testimonials">Testimonials</a>
                        </li>  

                        <li>
                            <a href="#packages">Packages</a>
                        </li>
                        <li>
                            <a href="#contact">Contactus</a>
                        </li> 
                        <li>
                            <a href="#" data-toggle="modal" data-target="#signin-page" data-modal-form="sign-in" class="nav-link sidebar-login mob_connection">
                                Login
                            </a>                            
                        </li>
                        <li>
                            <a href="#" data-toggle="modal" data-target="#signin-page" data-modal-form="sign-up" class="text-smaller sidebar-signup mob_connection">
                                Signup
                            </a>
                        </li>
                        <li>
                            <div class="mobile-sidebar-none">                                                  
                                <span class="sidebar-btn btn fa-bar-hide" data-action="toggle" data-side="right">
                                    <i class="fa fa-bars"></i>
                                </span>                  
                            </div>
                        </li>
                    </ul>                           
                </div>  

            </div>   
        </nav> 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStores</title>

    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="/assets/admin/favicon_1.ico">
    <link rel="icon" href="/assets/favicon_1.ico" type="image/x-icon">

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <!--Preloader-->                
    <aside class="left-panel">
      <!-- brand -->
      <div class="logo">
          <a href="index-2.html" class="logo-expanded">
              <i class="ion-social-buffer"></i>
              <span class="nav-label">My Store</span>
          </a>
      </div>
      <!-- / brand -->     
      <%= render :partial => "layouts/admin_left_accordian" %>
    </aside>
    <section class="content">
    <%= render :partial => "layouts/admin_header" %>
    <div class="wraper container-fluid">
      <%= yield %>
    </div>
    </section>
        <!-- Footer Start -->
    <footer class="footer">
        2016 © My Store.
    </footer>
    <!-- Footer Ends -->


  </body>
</html>
<%= render :partial => "layouts/not_loaded_js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStores</title>

    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">

    <%= stylesheet_link_tag    'landing', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <%= javascript_include_tag 'landing', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--Preloader-->                     
    <div id="btry-loader">
        <div class="btry inner">
            <div class="btry-charge"></div>
        </div>
    </div>

    <%= render :partial => "layouts/landing_header" %>
      <%= yield %>
    <%= render :partial => "layouts/landing_footer" %>
  </body>
</html>